spring.application.name=demo.todo

spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET}
jwt.access-expiration-seconds=600
jwt.refresh-expiration-seconds=604800

app.base-url=https://pmsaas.fly.dev
resend.api-key=${RESEND_API_KEY}
resend.from-email=${RESEND_FROM_EMAIL:no-reply@plannr.cloud}

spring.data.redis.url=${REDIS_URL}
